name: Actualizar Catálogo OPDS

on:
  push:
    branches: [ main, master ]
  schedule:
    - cron: '0 */6 * * *' # Se ejecuta automáticamente cada 6 horas
  workflow_dispatch: # Permite darle al botón de "Re-run" manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Copiar repositorio
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Ejecutar generador
      run: python generador.py

    - name: Subir cambios a GitHub Pages
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Actualización automática del catálogo XML"
        file_pattern: catalogo.xml
