name: Actualizar Catálogo OPDS
 
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'
 
permissions:
  contents: write
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
 
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
 
      - run: pip install requests beautifulsoup4 cloudscraper
 
      - run: python generador.py
 
      - run: |
          git status
          git diff --name-only
 
      - uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "Actualización automática del catálogo XML"
          file_pattern: |
            catalogo.xml
            catalogo-*.xml
